#!/bin/sh
base=`dirname $R`
test -z $base && exit 1
rm -rf $base REPO
mkdir -p $base
svnadmin create $R
svn co file://$R
cd REPO
echo test > testfile
svn add testfile
svn commit -m "add"
echo -n > testfile
svn commit -m "empty"
echo -e '#!/bin/sh\necho OK' > script.sh
chmod a+x script.sh
svn add script.sh
svn commit -m "add script"
echo echo changed >> script.sh
svn commit -m "change script"
cd ..
svnadmin dump $R > $R.dump
